import { useEffect, useMemo, useRef, useState } from 'react'

const WORDS=['ROAD','CARS','NOTE','PLAY','DRIVE','LAMP','LIFT','GLOW','SONG','RACE','HOPS','DRUM','OWLS','TREE','ROCK','FLOW','GEMS','LIGHT','MOON','STAR','RING','COMET','SPACE','MUSIC','FINISH']
const NOTES=['C','D','E','F']; const FREQ=[261.63,293.66,329.63,349.23]
const PATTERNS=[[0,0,1],[0,1,0],[0,1,2],[0,2,1],[1,2,3],[0,1,3],[0,2,3],[1,3,2]]
const BOSS_LEVELS=new Set([9,14,19,24])
function tone(i){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=tone.c||(tone.c=new A());const o=c.createOscillator(),g=c.createGain();o.frequency.value=FREQ[i];g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.15,c.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.25);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.28)}catch{}}
export default function LearningHUD(){
 const [playing,setPlaying]=useState(false),[level,setLevel]=useState(0),[hits,setHits]=useState(0),[mode,setMode]=useState('word'),[msg,setMsg]=useState(''); const [step,setStep]=useState(0); const last=useRef(-1),beat=useRef(performance.now());
 const word=WORDS[level]||'GO'; const pattern=useMemo(()=>PATTERNS[level%PATTERNS.length],[level]); const boss=BOSS_LEVELS.has(level)
 useEffect(()=>{const sync=()=>{setPlaying(!!document.querySelector('.play-screen .controller'));const m=(document.querySelector('.hud-copy b')?.textContent||'').match(/LEVEL\s+(\d+)/i);if(m){const n=+m[1]-1;if(n!==last.current){last.current=n;setLevel(n);setHits(0);setStep(0);setMsg('');setMode(n>=15?'listen':n>=10?'rhythm':'word')}}};const ob=new MutationObserver(sync);ob.observe(document.body,{subtree:true,childList:true,characterData:true});sync();return()=>ob.disconnect()},[])
 useEffect(()=>{if(!playing||boss||level<10||level>=15)return;const bpm=Math.min(108,76+(level-10)*5),iv=60000/bpm;const t=setInterval(()=>{beat.current=performance.now();setMsg('♪ BEAT');setTimeout(()=>setMsg(''),160)},iv);return()=>clearInterval(t)},[playing,boss,level])
 useEffect(()=>{if(!playing||boss||level<15)return;setMode('listen');setMsg('👂 LISTEN');const timers=pattern.map((n,i)=>setTimeout(()=>tone(n),350+i*480));const t=setTimeout(()=>{setMode('memory');setMsg('🚗 YOUR TURN')},450+pattern.length*480);return()=>{timers.forEach(clearTimeout);clearTimeout(t)}},[playing,boss,level,pattern])
 useEffect(()=>{const press=e=>{if(boss)return;const b=e.target.closest?.('.controller button');if(!b||b.disabled)return;const correct=b.classList.contains('hint');if(!correct)return;setHits(h=>Math.min(word.length,h+1));if(level>=15&&mode==='memory'){const p=NOTES.findIndex(n=>(b.textContent||'').includes(n));if(p===pattern[step]){tone(p);const s=step+1;setStep(s);setMsg(s===pattern.length?'⭐ MEMORY MASTER!':'NICE!');if(s===pattern.length)setTimeout(()=>{setMode('word');setMsg('')},850)}else{setStep(0);setMsg('↻ TRY THE TUNE AGAIN')}}else if(level>=10&&level<15){const d=Math.abs(performance.now()-beat.current);setMsg(d<190?'⚡ PERFECT!':'🏎️ KEEP RACING!');setTimeout(()=>setMsg(''),450)}};document.addEventListener('pointerdown',press,true);return()=>document.removeEventListener('pointerdown',press,true)},[boss,level,mode,pattern,step,word.length])
 if(!playing||boss)return null; const shown=Math.min(word.length,hits);
 return <div style={{position:'fixed',left:'50%',top:116,transform:'translateX(-50%)',zIndex:46,pointerEvents:'none',background:'rgba(20,67,139,.9)',border:'3px solid white',borderRadius:18,padding:'6px 12px',boxShadow:'0 4px 0 rgba(6,38,85,.7)',color:'#fff',textAlign:'center',minWidth:150}}>
  <div style={{fontSize:10,fontWeight:1000,letterSpacing:'.05em'}}>{msg||(mode==='memory'?'PLAY IT BACK':level>=15?'MUSIC MEMORY':level>=10?'RHYTHM RACE':'WORD RIDE')}</div>
  {mode==='memory'?<div style={{display:'flex',justifyContent:'center',gap:5,marginTop:4}}>{pattern.map((_,i)=><span key={i} style={{width:20,height:20,borderRadius:10,border:'2px solid white',background:i<step?'#6ee58b':'rgba(255,255,255,.18)'}}>{i<step?'✓':'♪'}</span>)}</div>:<div style={{fontWeight:1000,letterSpacing:3,marginTop:3,fontSize:15}}>{word.split('').map((c,i)=><span key={i} style={{opacity:i<shown?1:.28}}>{i<shown?c:'•'}</span>)}</div>}
 </div>
}
