import { useEffect, useRef, useState } from 'react'

const TYPES=['collect','race','gates','rhythm','choice','chase','memory','collect','race','finale','rhythm','gates','chase','choice','finale','memory','race','collect','gates','finale','chase','rhythm','choice','memory','finale']
const META={collect:['⭐','COLLECT RUN','Collect the road stars'],race:['🏁','RIVAL RACE','Catch the rival before the finish'],gates:['🚦','GATE RUN','Open every music gate'],rhythm:['🥁','RHYTHM RUN','Hold the groove'],choice:['↗','ROUTE PICK','Earn the shortcut'],chase:['🏎️','CHASE','Follow and catch the music car'],memory:['👂','MEMORY CHASE','Listen, remember, chase'],finale:['🎵','WORLD FINALE','Finish the world challenge']}
export default function MissionDirector(){
 const [playing,setPlaying]=useState(false),[level,setLevel]=useState(0),[hits,setHits]=useState(0),[misses,setMisses]=useState(0),[flash,setFlash]=useState(''),[route,setRoute]=useState('main');const last=useRef(-1),rivalClock=useRef(null)
 const type=TYPES[level]||'collect',meta=META[type],target=type==='finale'?6:type==='race'||type==='chase'?5:4,progress=Math.min(target,hits),rival=Math.min(target,Math.floor(misses*.8)+Math.floor(hits/3))
 useEffect(()=>{const sync=()=>{setPlaying(!!document.querySelector('.play-screen .controller'));const m=(document.querySelector('.hud-copy b')?.textContent||'').match(/LEVEL\s+(\d+)/i);if(m){const n=+m[1]-1;if(n!==last.current){last.current=n;setLevel(n);setHits(0);setMisses(0);setRoute('main');setFlash('')}}};const ob=new MutationObserver(sync);ob.observe(document.body,{childList:true,subtree:true,characterData:true});sync();return()=>ob.disconnect()},[])
 useEffect(()=>{if(!playing||!(type==='race'||type==='chase'))return;clearInterval(rivalClock.current);rivalClock.current=setInterval(()=>setMisses(v=>v+1),2600);return()=>clearInterval(rivalClock.current)},[playing,type,level])
 useEffect(()=>{const press=e=>{const b=e.target.closest?.('.controller button');if(!b||b.disabled||!playing)return;if(b.classList.contains('hint')){const next=hits+1;setHits(next);setFlash(type==='collect'?'⭐ COLLECTED!':type==='gates'?'🚦 OPEN!':type==='race'?'💨 GAINING!':type==='chase'?'🏎️ CLOSER!':type==='choice'&&next>=3?'↗ SHORTCUT OPEN!':type==='finale'?'🎵 SHOWTIME!':'✓ NICE!')}else{setMisses(v=>v+1);setFlash(type==='race'||type==='chase'?'RIVAL GAINS!':'RECOVER!')}setTimeout(()=>setFlash(''),450)};document.addEventListener('pointerdown',press,true);return()=>document.removeEventListener('pointerdown',press,true)},[playing,type,hits])
 if(!playing)return null
 const wonRace=(type==='race'||type==='chase')&&progress>=target&&progress>rival,lostRace=(type==='race'||type==='chase')&&rival>=target&&progress<target
 return <><div className={`mission-director mission-${type}`}><div className="mission-icon">{meta[0]}</div><div className="mission-text"><b>{meta[1]}</b><small>{wonRace?'🏆 YOU CAUGHT THEM!':lostRace?'↻ CATCH UP!':flash||meta[2]}</small></div><div className="mission-meter">{Array.from({length:target},(_,i)=><i key={i} className={i<progress?'done':''}/>)}</div>{(type==='race'||type==='chase')&&<div className="mini-race"><span className="you" style={{left:`${8+progress/target*70}%`}}>🚙</span><span className="rival" style={{left:`${8+rival/target*70}%`}}>🏎️</span></div>}{type==='choice'&&progress>=3&&<div className="route-choice interactive"><button onPointerDown={()=>setRoute('main')}>ROAD</button><button onPointerDown={()=>setRoute('shortcut')}>↗ SHORTCUT</button></div>}</div>
 <div className={`mission-road-layer ${type} route-${route}`} aria-hidden="true">{type==='collect'&&Array.from({length:4},(_,i)=><span key={i} className={`road-star s${i} ${i<progress?'taken':''}`}>★</span>)}{type==='gates'&&Array.from({length:4},(_,i)=><span key={i} className={`road-gate g${i} ${i<progress?'open':''}`}>▮ ▮</span>)}{type==='choice'&&progress>=3&&<span className="physical-shortcut">↗</span>}{(type==='race'||type==='chase')&&<span className="physical-rival" style={{bottom:`${22+Math.max(0,rival-progress)*7}%`}}>🏎️</span>}{type==='finale'&&<div className="finale-lights">♪ ★ ♪ ★ ♪</div>}</div></>
}
